archive = "bionic"
version = "18.04"
origin = "system76-cuda"
label = "System76 CUDA Repo"
email = "michael@system76.com"

[[source]]
name = "system76-cuda"
location = { path = ".." }

    # Artifacts are files which we have cached in advance.
    [[source.artifacts]]
    src = "9.0/*"  # Where the assets can be found (globbed)
    dst = "cuda-9.0"      # Where the assets should be stored.

    [[source.artifacts]]
    src = "9.1/*"
    dst = "cuda-9.1"

    [[source.artifacts]]
    src = "9.2/*"
    dst = "cuda-9.2"

    [[source.artifacts]]
    src = "cudnn-9.0/*"
    dst = "cudnn-9.0"

    [[source.artifacts]]
    src = "cudnn-9.2/*"
    dst = "cudnn-9.2"

    # If a project contains sub-projects, list the members here.
    [[source.members]]
    name = "system76-cuda"  # The name of the project's source package
    directory = "cuda"      # The directory of the sub-project
    priority = 0            # The order which the package should be built
    build_on = "changelog"  # The condition for building a package

    [[source.members]]
    name = "system76-cuda-9-0"
    directory = "cuda-9.0"
    priority = 1
    build_on = "changelog"

    [[source.members]]
    name = "system76-cuda-9-1"
    directory = "cuda-9.1"
    priority = 1
    build_on = "changelog"

    [[source.members]]
    name = "system76-cuda-9-2"
    directory = "cuda-9.2"
    priority = 1
    build_on = "changelog"

    [[source.members]]
    name = "system76-cudnn-9-0"
    directory = "cudnn-9.0"
    priority = 2
    build_on = "changelog"

    [[source.members]]
    name = "system76-cudnn-9-2"
    directory = "cudnn-9.2"
    priority = 2
    build_on = "changelog"

[[direct]]
name = "bazel"
version = "0.15"
arch = "amd64"
url = "https://github.com/bazelbuild/bazel/releases/download/0.15.0/bazel_0.15.0-linux-x86_64.deb"
checksum = "387e0a8f8b99d89d8e60486cb03bf7a7"

# [[source]]
# name = "tensorflow"
# debian = { path = "../tensorflow" }
#
#     [source.location]
#     url = "https://github.com/tensorflow/tensorflow/archive/v1.7.1.tar.gz"
#     checksum = "33ed4afb5b11b20090e2f6314c867f6c"
