archive = "disco"
version = "19.04"
origin = "system76"
label = "System76"
email = "info@system76.com"

extra_repos = [ "deb http://ppa.launchpad.net/system76/pop/ubuntu disco main" ]

[[source]]
name = "system76-cuda"
build_on = "changelog"
assets = [
    { src = "nvidia_cuda/*", dst = "debian"}
]

[[source]]
name = "system76-cuda-10.1"
build_on = "changelog"
keep_source = false
retain = 1
assets = [
    { src = "cuda_makefile_v2", dst = "Makefile" },
]

[[source]]
name = "system76-cudnn-10.1"
build_on = "changelog"
assets = [
    { src = "nvidia_cuda/*", dst = "debian"}
]
retain = 1
keep_source = false

[[source]]
name = "system76-nccl-10.1"
build_on = "changelog"
depends = [
    "system76-cuda",
    "system76-cuda-10.1",
]

    [source.location]
    url = "https://github.com/NVIDIA/nccl/archive/v2.4.2-1.tar.gz"
    checksum = "e3dd04b22eb541394bd818e5f78ac23a09cc549690d5d55d6fccc1a36155385a"

# Build system required by tensorflow
[[source]]
name = "bazel"
build_on = "changelog"

    [source.location]
    url = "https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel-0.21.0-dist.zip"
    checksum = "6ccb831e683179e0cfb351cb11ea297b4db48f9eab987601c038aa0f83037db4"

# [[source]]
# name = "tensorflow-1.12-cuda-10.0"
# build_on = "changelog"
# retain = 1
# assets = [
#     { src = "tensorflow-1.12/*", dst = "." },
#     { src = "tensorflow/*", dst = "debian" }
# ]
# depends = [
#     "bazel",
#     "system76-cuda",
#     "system76-cuda-10.0",
#     "system76-cudnn-10.0",
#     "system76-nccl-10.0",
# ]

# [[source]]
# name = "tensorflow-1.12-cpu"
# build_on = "changelog"
# retain = 1
# assets = [
#     { src = "tensorflow-1.12/*", dst = "." },
#     { src = "tensorflow/*", dst = "debian" }
# ]
# depends = [ "bazel" ]
